---
apiVersion: v1
kind: Service
metadata:
  CreationTimestamp: null
  labels:
    app: bgd
  name: bgd
  namespace: bgd
spec:
  selector:
    app: bgd
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080